services:
  db:
    image: postgres:16
    container_name: aiant_postgres
    restart: always
    environment:
      POSTGRES_DB: aiant_project_db
      POSTGRES_USER: aiant
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    environment:
      - PYTHONPATH=/app
    container_name: extract
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /app
    command: ["python", "-u", "src/extract/extract.py"]

volumes:
  db_data: