services:
  db:
    image: postgres:16
    container_name: aiant_postgres
    restart: always
    environment:
      POSTGRES_DB: aiant_project_db
      POSTGRES_USER: aiant
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aiant -d aiant_project_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  extractor:
    build: .
    environment:
      - PYTHONPATH=/app
    container_name: extractor
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    working_dir: /app
    command: ["python", "-u", "-m", "src.extract.extract"]

  transformer:
    build: .
    environment:
      - PYTHONPATH=/app
    container_name: transformer
    depends_on:
      extractor:
        condition: service_completed_successfully
    env_file:
      - .env
    working_dir: /app
    command: ["python", "-u", "-m", "src.transform.transform"]

volumes:
  db_data: